### ISSUE TITLE
Is it possible to dump "Dependency of" or the root node of "paths"?

### ISSUE THREAD

**Issue by Mrks83** [cy6erskunk/npm-audit-reporter-teamcity#142]
To see the cause of an issue in TeamCity I would like to see the root "Dependency of".

**Comment by cy6erskunk** [comment]
That actually sounds like a good idea which should be somewhat easy to implement, thank you for the suggestion @Mrks83

**Comment by cy6erskunk** [comment]
@Mrks83 it should now be available in version `0.3.0`, could you try it out?

**Comment by Mrks83** [comment]
> 
> 
> @Mrks83 it should now be available in version `0.3.0`, could you try it out?

I tried `0.3.1` and it worked like a charm :)
